### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by minwook-shin** [minwook-shin/kookmin-university-home#1]
- [ ] 쿠키 제거 기능 추가

- [ ]  파이어폭스 확장기능 제작

- [ ] 아이콘 제작

- [ ] 자체 레이아웃 개발
